In [71]:
import os

def listar_arquivos_excel(diretorio):
    """
    Retorna todos os arquivos .xlsx ou .xls de um diretório.

    Parâmetros:
    diretorio (str): O caminho do diretório.

    Retorna:
    lista_arquivos (list): Uma lista de arquivos .xlsx ou .xls no diretório.
    """
    lista_arquivos = []
    
    try:
        # Iterar sobre os arquivos no diretório
        for arquivo in os.listdir(diretorio):
            # Verificar se o arquivo termina com .xlsx ou .xls
            if arquivo.endswith('.xlsx') or arquivo.endswith('.xls'):
                lista_arquivos.append(arquivo)
        
        return lista_arquivos
    except Exception as e:
        print(f"Erro ao listar arquivos no diretório: {e}")
        return []

# Exemplo de uso da função
def mover_arquivo(caminho_origem, caminho_destino):
    """
    Move um arquivo de uma pasta para outra.

    Parâmetros:
    caminho_origem (str): O caminho completo do arquivo de origem.
    caminho_destino (str): O caminho completo do arquivo de destino.
    """
    try:
        # Verifica se o arquivo de origem existe
        if not os.path.exists(caminho_origem):
            raise FileNotFoundError(f"Arquivo de origem não encontrado: {caminho_origem}")

        # Cria o diretório de destino se ele não existir
        os.makedirs(os.path.dirname(caminho_destino), exist_ok=True)
        
        # Move o arquivo
        shutil.move(caminho_origem, caminho_destino)
        print(f"Arquivo movido com sucesso de {caminho_origem} para {caminho_destino}")
    except Exception as e:
        print(f"Erro ao mover o arquivo: {e}")

In [81]:
import pandas as pd
from openpyxl import load_workbook
import shutil
import os


arquivos_pendentes = listar_arquivos_excel (r"C:\TLV\GENOMMA\PENDENCIA")
for arquivo in arquivos_pendentes: 
    
    arquivos_excel = listar_arquivos_excel(r"C:\TLV\GENOMMA\HISTORICO")
    num_arquivos = len(arquivos_excel)
    contador = num_arquivos + 1


    # Carregar o arquivo Excel de origem e extrair os dados para um DataFrame
    df = pd.read_excel(rf"C:\TLV\GENOMMA\PENDENCIA\{arquivo}")

    dataframe_historico = pd.read_excel(r"C:\TLV\GENOMMA\MODELO\GenommaImportacao1.xlsx")

    colunas_df=[
    'Nº Tarefa',
    'CNPJ Fornecedor',
    'Descrição Produto',
    'Preço Unitário',
    'Quantidade',
    'Cod. EAN']
    df=df[colunas_df]



    colunas_desejadas = ['NR_PEDIDO','CNPJ','DESCRICAO','PRECO','QTDE','EAN']
    df.columns = colunas_desejadas
    display(df)


    # Exibir os nomes das colunas para garantir a compatibilidade
    print("DataFrame Columns:", df.columns)
    print("DataFrame Historico Columns:", dataframe_historico.columns)

    # Adicionar colunas ausentes do dataframe_historico ao df
    for col in dataframe_historico.columns:
        if col not in df.columns:
            df[col] = pd.NA

    # Garantir que as colunas do df estejam na mesma ordem do dataframe_historico
    df = df.reindex(columns=dataframe_historico.columns.tolist() + [col for col in df.columns if col not in dataframe_historico.columns])

    # Concatenar os dois DataFrames
    df_final = pd.concat([dataframe_historico, df], axis=0, ignore_index=True)

    # Exibir o DataFrame final
    display(df_final)


    mover_arquivo(rf"C:\TLV\GENOMMA\PENDENCIA\{arquivo}", rf"C:\TLV\GENOMMA\HISTORICO\Pedido_Genoma-{contador}.xlsx")
    

    df_final.to_excel(rf"C:\TLV\GENOMMA\PEDIDO\Pedido_Genomma{contador}.xlsx")

,NR_PEDIDO,CNPJ,DESCRICAO,PRECO,QTDE,EAN
0,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","2,000",7898949409922
1,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","1,000",7898949409922
2,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","1,000",7898949409922
3,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","1,000",7898949409922
4,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","2,000",7898949409922
...,...,...,...,...,...,...
2708,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"19,11","1,000",7898636191079
2709,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","2,000",7898636191079
2710,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","2,000",7898636191079
2711,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","2,000",7898636191079
2712,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","1,000",7898636191079

DataFrame Columns: Index(['NR_PEDIDO', 'CNPJ', 'DESCRICAO', 'PRECO', 'QTDE', 'EAN'], dtype='object')
DataFrame Historico Columns: Index(['CNPJ', 'CODIGO', 'DESCRICAO', 'NR_PEDIDO', 'QTDE', 'PROMOCAO', 'PRAZO',
       'PRECO', 'DESCONTO', 'PRECO_FINAL', 'EAN', 'OL', 'VALOR_COTADO',
       'ID_DESCONTO_INFORMADO', 'COD_PRAZO', 'COD_CLIENTE', 'NR_BLOQUEIO'],
      dtype='object')

,CNPJ,CODIGO,DESCRICAO,NR_PEDIDO,QTDE,PROMOCAO,PRAZO,PRECO,DESCONTO,PRECO_FINAL,EAN,OL,VALOR_COTADO,ID_DESCONTO_INFORMADO,COD_PRAZO,COD_CLIENTE,NR_BLOQUEIO
0,82873068000573,NaN,SH TIO NACHO 415ML ENGROSSADOR,44101,"2,000",NaN,NaN,"29,20",NaN,NaN,7898949409922,NaN,NaN,NaN,NaN,NaN,NaN
1,82873068000573,NaN,SH TIO NACHO 415ML ENGROSSADOR,44101,"1,000",NaN,NaN,"29,20",NaN,NaN,7898949409922,NaN,NaN,NaN,NaN,NaN,NaN
2,82873068000573,NaN,SH TIO NACHO 415ML ENGROSSADOR,44101,"1,000",NaN,NaN,"29,20",NaN,NaN,7898949409922,NaN,NaN,NaN,NaN,NaN,NaN
3,82873068000573,NaN,SH TIO NACHO 415ML ENGROSSADOR,44101,"1,000",NaN,NaN,"29,20",NaN,NaN,7898949409922,NaN,NaN,NaN,NaN,NaN,NaN
4,82873068000573,NaN,SH TIO NACHO 415ML ENGROSSADOR,44101,"2,000",NaN,NaN,"29,20",NaN,NaN,7898949409922,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,82873068000573,NaN,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,44101,"1,000",NaN,NaN,"19,11",NaN,NaN,7898636191079,NaN,NaN,NaN,NaN,NaN,NaN
2709,82873068000573,NaN,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,44101,"2,000",NaN,NaN,"17,81",NaN,NaN,7898636191079,NaN,NaN,NaN,NaN,NaN,NaN
2710,82873068000573,NaN,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,44101,"2,000",NaN,NaN,"17,81",NaN,NaN,7898636191079,NaN,NaN,NaN,NaN,NaN,NaN
2711,82873068000573,NaN,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,44101,"2,000",NaN,NaN,"17,81",NaN,NaN,7898636191079,NaN,NaN,NaN,NaN,NaN,NaN
2712,82873068000573,NaN,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,44101,"1,000",NaN,NaN,"17,81",NaN,NaN,7898636191079,NaN,NaN,NaN,NaN,NaN,NaN

Arquivo movido com sucesso de C:\TLV\GENOMMA\PENDENCIA\TERCEIRO_GENOMMA.xlsx para C:\TLV\GENOMMA\HISTORICO\Pedido_Genoma-3.xlsx

,NR_PEDIDO,CNPJ,DESCRICAO,PRECO,QTDE,EAN
0,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","2,000",7898949409922
1,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","1,000",7898949409922
2,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","1,000",7898949409922
3,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","1,000",7898949409922
4,44101,82873068000573,SH TIO NACHO 415ML ENGROSSADOR,"29,20","2,000",7898949409922
...,...,...,...,...,...,...
2708,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"19,11","1,000",7898636191079
2709,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","2,000",7898636191079
2710,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","2,000",7898636191079
2711,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","2,000",7898636191079
2712,44101,82873068000573,ASEPXIA SAB LIQ 100ML ESFOLIANTE GENOMMA,"17,81","1,000",7898636191079

Empty DataFrame
Columns: [CNPJ, CODIGO, DESCRICAO, NR_PEDIDO, QTDE, PROMOCAO, PRAZO, PRECO, DESCONTO, PRECO_FINAL, EAN, OL, VALOR_COTADO, ID_DESCONTO_INFORMADO, COD_PRAZO, COD_CLIENTE, NR_BLOQUEIO]
Index: []